In [73]:
parent_dir = "/Users/mattan"
project_path = "/thesis/SFT/data"
wd = f"{parent_dir}{project_path}"

In [5]:
import csv

import pandas
%pip install datasets

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets in /Users/mattan/Library/Python/3.9/lib/python/site-packages (2.20.0)
Requirement already satisfied: filelock in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (3.15.4)
Requirement already satisfied: numpy>=1.17 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (2.0.0)
Requirement already satisfied: pyarrow>=15.0.0 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (16.1.0)
Requirement already satisfied: pyarrow-hotfix in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /Library/Python/3.9/site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (4.66.4)
Requirement already satisfied: xxhash in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (3.4.1)
Requirement already satisfied: multiprocess in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.5.0,>=2023.1.0 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from fsspec[http]<=2024.5.0,>=2023.1.0->datasets) (2024.5.0)
Requirement already satisfied: aiohttp in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (3.9.5)
Requirement already satisfied: huggingface-hub>=0.21.2 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (0.23.4)
Requirement already satisfied: packaging in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /Library/Python/3.9/site-packages (from datasets) (6.0.1)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /Library/Python/3.9/site-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from huggingface-hub>=0.21.2->datasets) (4.8.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Python/3.9/site-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Python/3.9/site-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Python/3.9/site-packages (from requests>=2.32.2->datasets) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/3.9/site-packages (from requests>=2.32.2->datasets) (2024.7.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Python/3.9/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
from datasets import load_dataset

# Load the IMDB dataset
dataset = load_dataset('dhmeltzer/ask-science-qg')

# Print the first example in the training set
print(dataset['train'][0])

# Display dataset information
print(dataset)

/Library/Python/3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

{'title': 'what are the long-term effects of using raid?', 'selftext': "i'm talking about the one you plug into the wall. when it kills insects, it surely can't be good for my lungs and brain, or are the doses simply low enough not to be harmful? what are the long-term effects, then?", 'answers.text': "i did some research as a layman. one forum user [claims it contains](_url_1_) 300mg of transfluthrin, but i can't seem to find any sc johnson or raid site that corroborates that. transfluthrin is a pyrethroid, related to a pesticide produced by chrysanthemums called pyrethrum. the epa has [scant information on pyrethroids](_url_0_), but the consensus seems to be that low doses are mostly harmless.", 'answers.score': 3, 'title_urls.url': [], 'selftext_urls.url': [], 'answers_urls.url': ['http://www.epa.gov/pesticides/health/mosquitoes/pyrethroids4mosquitoes.htm', 'http://www.shanghaiexpat.com/phpbbforum/raid-plug-ins-is-it-deet-free-t112291.html'], 'sent_vec': [-0.7255505919456482, -0.003705620765686035, -0.6605789661407471, -0.9549583196640015, 1.1785768270492554, -0.45838603377342224, 0.8508591651916504, 1.0482252836227417, -0.6155848503112793, -0.7686198949813843, 0.7310305237770081, 0.07271027565002441, 0.07995486259460449, 0.5615687370300293, 0.6900725364685059, -0.2412843406200409, 0.7364736795425415, -1.1228086948394775, 0.4777783155441284, 0.3262585997581482, -0.28374895453453064, 1.6175569295883179, 0.5955187678337097, 0.511100709438324, -0.4910006821155548, -0.5436519384384155, -0.46288421750068665, 0.29690566658973694, -0.3154555857181549, -0.05731221288442612, -0.4832935333251953, 1.3867132663726807, -1.3953311443328857, -0.3483455181121826, -0.04913189262151718, -1.0132771730422974, -0.9409132599830627, 0.17989444732666016, 0.6255019903182983, 0.5489581823348999, -0.12876707315444946, 0.10089732706546783, -0.9448466300964355, 0.6149706840515137, -1.044508457183838, -0.07357308268547058, -0.3839132785797119, 0.3307129740715027, -0.5531113743782043, -0.39855897426605225, 1.0696812868118286, 0.03925669193267822, -0.5077837705612183, 1.1558656692504883, 1.0973191261291504, -1.9675004482269287, -1.2809333801269531, -0.556003212928772, -0.9620449542999268, -0.04009220004081726, -0.13174094259738922, 0.55538010597229, -1.4998594522476196, 0.2856186330318451, 0.10843431949615479, 1.0627423524856567, 0.23773087561130524, -0.6967437267303467, 1.5735468864440918, 0.22677290439605713, -0.36878782510757446, -0.004685729742050171, -0.47404274344444275, 1.0222598314285278, -0.7861779928207397, 0.25309330224990845, 0.09508755058050156, 0.49353641271591187, -0.1857030689716339, -0.5728816390037537, -0.8602582812309265, 0.4126831293106079, 0.9174937009811401, 0.5321619510650635, -0.049978017807006836, -0.17230930924415588, 0.46385669708251953, 1.4912497997283936, 0.0431763231754303, 0.1130569577217102, -0.6982657313346863, 1.486598014831543, -0.1624392569065094, 0.22989535331726074, -0.7062329053878784, 1.2650094032287598, 1.0528123378753662, -0.019090518355369568, -1.0171035528182983, 1.544553518295288, -1.0498337745666504, -0.9684882164001465, -1.774916172027588, -0.2391199767589569, 0.38392335176467896, -0.39982569217681885, 0.5450271368026733, 0.6820834875106812, 0.33199939131736755, 0.09752773493528366, -0.3643844723701477, 0.685961127281189, 0.1815194934606552, 0.1393355131149292, 0.10843540728092194, -0.5409760475158691, 0.039575427770614624, -0.02513578161597252, -0.7105093002319336, -0.6671932935714722, 0.3639281690120697, 0.9283304810523987, 0.7147669792175293, 0.36802101135253906, 0.9606180191040039, 0.7804251313209534, 0.771672248840332, 0.6587181091308594, 0.37913942337036133, 1.3706798553466797, 0.5260310173034668, -0.7236979603767395, 0.593049168586731, 0.40479961037635803, -0.25152894854545593, -0.30709290504455566, -0.13005799055099487, 0.2160225212574005, -0.5377644896507263, 0.6441632509231567, -0.9947337508201599, 0.7194046974182129, -0.5567602515220642, 0.9959844350814819, -0.3712312579154968, 1.4540071487426758, 0.30231890082359314, -0.7804475426673889, -0.7243222594261169, 1.013242244720459, -0.19760018587112427, 0.4542786180973053, -0.582022488117218, 0.7454156279563904, -0.7555918097496033, -0.03820929676294327, 0.8141480088233948, 0.31329262256622314, 1.4190175533294678, -0.18580983579158783, -0.48220139741897583, 0.13230927288532257, 0.2426493614912033, 0.5191774964332581, -0.9579929709434509, -0.19316864013671875, -1.180626630783081, -0.12745019793510437, -0.048479124903678894, 0.30163267254829407, -0.23744255304336548, -0.6422297358512878, 0.5607903003692627, -1.395583152770996, -1.3366379737854004, -0.5036786198616028, -0.42485207319259644, 1.0372644662857056, 0.551257848739624, 0.5196108222007751, -0.07189829647541046, 1.1568917036056519, -0.9827945232391357, 0.46226435899734497, -0.5082601308822632, 0.07237215340137482, 0.17064978182315826, -0.38607603311538696, -0.5900638103485107, -0.355351984500885, -2.4060821533203125, -0.6815676689147949, 0.9545533657073975, -0.12066520750522614, -0.627246618270874, -0.3880288004875183, -0.5698925852775574, -0.014936506748199463, 0.9166005849838257, -0.5042012333869934, 0.4813970923423767, -0.5081249475479126, 1.023249626159668, -0.9907490015029907, 0.41090309619903564, 0.5907599329948425, 0.4864232838153839, -1.3991103172302246, -0.8129428625106812, -1.0332105159759521, -0.5704267024993896, -0.5741279125213623, -1.7385622262954712, -0.8339242935180664, 0.8492460250854492, 0.9486119151115417, 0.04426000267267227, -0.5721083879470825, 0.3232623338699341, 0.032965660095214844, -1.3335102796554565, -0.36717405915260315, -0.8026113510131836, -1.3768982887268066, -1.0784833431243896, -0.3452392816543579, 0.6980811953544617, 0.9300453066825867, 0.003918876871466637, 1.1958903074264526, -0.23933537304401398, 0.08224919438362122, 1.0655677318572998, 0.6202654838562012, -0.055054664611816406, 0.5246956944465637, 0.7275998592376709, -0.8714204430580139, 0.012372240424156189, 0.7508845329284668, 0.039228588342666626, 0.5515520572662354, -0.9345344305038452, 0.5715861320495605, -0.517876148223877, 0.4325488209724426, -0.5225116610527039, 0.2294730842113495, -0.29332542419433594, 1.4930191040039062, 0.20191335678100586, 0.06339395046234131, -0.8630067110061646, -0.4055565893650055, 1.283291220664978, 1.2583506107330322, -1.0307952165603638, -1.0796175003051758, -0.005660302937030792, -0.3026241064071655, -0.42089661955833435, 0.2756170630455017, -0.8075771331787109, -0.8117283582687378, -0.2307356297969818, -0.4942043125629425, -1.1039083003997803, 1.236538290977478, -0.5735493302345276, -0.6888982653617859, 0.16266217827796936, -0.6874724626541138, 1.169924259185791, -0.2184915542602539, 0.31304794549942017, 0.5169081091880798, 0.9932178258895874, -0.17399895191192627, 0.060566484928131104, -0.05606124550104141, -0.15554611384868622, -0.7588722109794617, 0.8253175020217896, 0.3706430196762085, 0.32575076818466187, -0.2899280786514282, -1.4988551139831543, -0.2508699297904968, -0.49109241366386414, -0.1899966597557068, -0.2825416624546051, 0.7535319328308105, 1.5006171464920044, -0.4885074496269226, 0.9721674919128418, 0.129302978515625, 0.5406212210655212, -1.036348819732666, -0.6927956342697144, -0.915047824382782, -0.37214991450309753, -0.719666063785553, -0.34084659814834595, 0.025622501969337463, 1.516902208328247, -0.11366254091262817, -0.1293836534023285, -0.4358983039855957, 0.8788203001022339, -1.0164110660552979, -0.002903580665588379, -0.8069247603416443, 0.3148723244667053, 0.17869886755943298, 0.40456831455230713, -0.3473779857158661, -1.2967467308044434, 1.1127665042877197, 0.972009539604187, 0.18289506435394287, 1.6633230447769165, 0.7461077570915222, 0.5575858950614929, 0.9826512932777405, 0.3378932476043701, 0.8871616721153259, -0.2932049632072449, 0.08786389231681824, 0.319000780582428, 0.7508746981620789, 1.040123701095581, -0.14301498234272003, 0.4140048027038574, -0.4061390161514282, -0.15741458535194397, 0.23856423795223236, -0.026092082262039185, -0.731031060218811, -0.4945276975631714, 0.204799085855484, -1.8118300437927246, 0.11866198480129242, -0.4098764955997467, -1.321239948272705, 0.41885316371917725, -0.14077168703079224, 1.6924793720245361, 0.06172633171081543, 0.39586806297302246, 0.4460594654083252, -0.14537522196769714, 0.4245929718017578, -0.5734315514564514, 0.58135986328125, 1.039180040359497, 0.2041945457458496, -0.7745007276535034, -0.018084466457366943, 0.8961354494094849, -0.2499942183494568, -0.11782808601856232, -0.19962918758392334, -0.7439751625061035, 0.38578835129737854, -0.26452481746673584, 0.14091208577156067, -0.5843343734741211, 0.3265976309776306, 0.9214553833007812, 0.5255436301231384, 0.9820154905319214, -0.23835523426532745, 0.2420089840888977, -0.09712211787700653, -1.3383541107177734, 0.155170276761055, 0.13503895699977875, -1.0548174381256104, -0.9445807933807373, -0.6331267356872559, 0.6995774507522583, -0.2910701632499695, 1.775974154472351, 0.1814315766096115]}
DatasetDict({
    train: Dataset({
        features: ['title', 'selftext', 'answers.text', 'answers.score', 'title_urls.url', 'selftext_urls.url', 'answers_urls.url', 'sent_vec'],
        num_rows: 125323
    })
    validation: Dataset({
        features: ['title', 'selftext', 'answers.text', 'answers.score', 'title_urls.url', 'selftext_urls.url', 'answers_urls.url', 'sent_vec'],
        num_rows: 2060
    })
    test: Dataset({
        features: ['title', 'selftext', 'answers.text', 'answers.score', 'title_urls.url', 'selftext_urls.url', 'answers_urls.url', 'sent_vec'],
        num_rows: 4058
    })
})

In [7]:
from pprint import pprint

In [8]:
pprint(dataset['train'][0])

{'answers.score': 3,
 'answers.text': 'i did some research as a layman. one forum user [claims it '
                 "contains](_url_1_) 300mg of transfluthrin, but i can't seem "
                 'to find any sc johnson or raid site that corroborates that. '
                 'transfluthrin is a pyrethroid, related to a pesticide '
                 'produced by chrysanthemums called pyrethrum. the epa has '
                 '[scant information on pyrethroids](_url_0_), but the '
                 'consensus seems to be that low doses are mostly harmless.',
 'answers_urls.url': ['http://www.epa.gov/pesticides/health/mosquitoes/pyrethroids4mosquitoes.htm',
                      'http://www.shanghaiexpat.com/phpbbforum/raid-plug-ins-is-it-deet-free-t112291.html'],
 'selftext': "i'm talking about the one you plug into the wall. when it kills "
             "insects, it surely can't be good for my lungs and brain, or are "
             'the doses simply low enough not to be harmful? what are the '
             'long-term effects, then?',
 'selftext_urls.url': [],
 'sent_vec': [-0.7255505919456482,
              -0.003705620765686035,
              -0.6605789661407471,
              -0.9549583196640015,
              1.1785768270492554,
              -0.45838603377342224,
              0.8508591651916504,
              1.0482252836227417,
              -0.6155848503112793,
              -0.7686198949813843,
              0.7310305237770081,
              0.07271027565002441,
              0.07995486259460449,
              0.5615687370300293,
              0.6900725364685059,
              -0.2412843406200409,
              0.7364736795425415,
              -1.1228086948394775,
              0.4777783155441284,
              0.3262585997581482,
              -0.28374895453453064,
              1.6175569295883179,
              0.5955187678337097,
              0.511100709438324,
              -0.4910006821155548,
              -0.5436519384384155,
              -0.46288421750068665,
              0.29690566658973694,
              -0.3154555857181549,
              -0.05731221288442612,
              -0.4832935333251953,
              1.3867132663726807,
              -1.3953311443328857,
              -0.3483455181121826,
              -0.04913189262151718,
              -1.0132771730422974,
              -0.9409132599830627,
              0.17989444732666016,
              0.6255019903182983,
              0.5489581823348999,
              -0.12876707315444946,
              0.10089732706546783,
              -0.9448466300964355,
              0.6149706840515137,
              -1.044508457183838,
              -0.07357308268547058,
              -0.3839132785797119,
              0.3307129740715027,
              -0.5531113743782043,
              -0.39855897426605225,
              1.0696812868118286,
              0.03925669193267822,
              -0.5077837705612183,
              1.1558656692504883,
              1.0973191261291504,
              -1.9675004482269287,
              -1.2809333801269531,
              -0.556003212928772,
              -0.9620449542999268,
              -0.04009220004081726,
              -0.13174094259738922,
              0.55538010597229,
              -1.4998594522476196,
              0.2856186330318451,
              0.10843431949615479,
              1.0627423524856567,
              0.23773087561130524,
              -0.6967437267303467,
              1.5735468864440918,
              0.22677290439605713,
              -0.36878782510757446,
              -0.004685729742050171,
              -0.47404274344444275,
              1.0222598314285278,
              -0.7861779928207397,
              0.25309330224990845,
              0.09508755058050156,
              0.49353641271591187,
              -0.1857030689716339,
              -0.5728816390037537,
              -0.8602582812309265,
              0.4126831293106079,
              0.9174937009811401,
              0.5321619510650635,
              -0.049978017807006836,
              -0.17230930924415588,
              0.46385669708251953,
              1.4912497997283936,
              0.0431763231754303,
              0.1130569577217102,
              -0.6982657313346863,
              1.486598014831543,
              -0.1624392569065094,
              0.22989535331726074,
              -0.7062329053878784,
              1.2650094032287598,
              1.0528123378753662,
              -0.019090518355369568,
              -1.0171035528182983,
              1.544553518295288,
              -1.0498337745666504,
              -0.9684882164001465,
              -1.774916172027588,
              -0.2391199767589569,
              0.38392335176467896,
              -0.39982569217681885,
              0.5450271368026733,
              0.6820834875106812,
              0.33199939131736755,
              0.09752773493528366,
              -0.3643844723701477,
              0.685961127281189,
              0.1815194934606552,
              0.1393355131149292,
              0.10843540728092194,
              -0.5409760475158691,
              0.039575427770614624,
              -0.02513578161597252,
              -0.7105093002319336,
              -0.6671932935714722,
              0.3639281690120697,
              0.9283304810523987,
              0.7147669792175293,
              0.36802101135253906,
              0.9606180191040039,
              0.7804251313209534,
              0.771672248840332,
              0.6587181091308594,
              0.37913942337036133,
              1.3706798553466797,
              0.5260310173034668,
              -0.7236979603767395,
              0.593049168586731,
              0.40479961037635803,
              -0.25152894854545593,
              -0.30709290504455566,
              -0.13005799055099487,
              0.2160225212574005,
              -0.5377644896507263,
              0.6441632509231567,
              -0.9947337508201599,
              0.7194046974182129,
              -0.5567602515220642,
              0.9959844350814819,
              -0.3712312579154968,
              1.4540071487426758,
              0.30231890082359314,
              -0.7804475426673889,
              -0.7243222594261169,
              1.013242244720459,
              -0.19760018587112427,
              0.4542786180973053,
              -0.582022488117218,
              0.7454156279563904,
              -0.7555918097496033,
              -0.03820929676294327,
              0.8141480088233948,
              0.31329262256622314,
              1.4190175533294678,
              -0.18580983579158783,
              -0.48220139741897583,
              0.13230927288532257,
              0.2426493614912033,
              0.5191774964332581,
              -0.9579929709434509,
              -0.19316864013671875,
              -1.180626630783081,
              -0.12745019793510437,
              -0.048479124903678894,
              0.30163267254829407,
              -0.23744255304336548,
              -0.6422297358512878,
              0.5607903003692627,
              -1.395583152770996,
              -1.3366379737854004,
              -0.5036786198616028,
              -0.42485207319259644,
              1.0372644662857056,
              0.551257848739624,
              0.5196108222007751,
              -0.07189829647541046,
              1.1568917036056519,
              -0.9827945232391357,
              0.46226435899734497,
              -0.5082601308822632,
              0.07237215340137482,
              0.17064978182315826,
              -0.38607603311538696,
              -0.5900638103485107,
              -0.355351984500885,
              -2.4060821533203125,
              -0.6815676689147949,
              0.9545533657073975,
              -0.12066520750522614,
              -0.627246618270874,
              -0.3880288004875183,
              -0.5698925852775574,
              -0.014936506748199463,
              0.9166005849838257,
              -0.5042012333869934,
              0.4813970923423767,
              -0.5081249475479126,
              1.023249626159668,
              -0.9907490015029907,
              0.41090309619903564,
              0.5907599329948425,
              0.4864232838153839,
              -1.3991103172302246,
              -0.8129428625106812,
              -1.0332105159759521,
              -0.5704267024993896,
              -0.5741279125213623,
              -1.7385622262954712,
              -0.8339242935180664,
              0.8492460250854492,
              0.9486119151115417,
              0.04426000267267227,
              -0.5721083879470825,
              0.3232623338699341,
              0.032965660095214844,
              -1.3335102796554565,
              -0.36717405915260315,
              -0.8026113510131836,
              -1.3768982887268066,
              -1.0784833431243896,
              -0.3452392816543579,
              0.6980811953544617,
              0.9300453066825867,
              0.003918876871466637,
              1.1958903074264526,
              -0.23933537304401398,
              0.08224919438362122,
              1.0655677318572998,
              0.6202654838562012,
              -0.055054664611816406,
              0.5246956944465637,
              0.7275998592376709,
              -0.8714204430580139,
              0.012372240424156189,
              0.7508845329284668,
              0.039228588342666626,
              0.5515520572662354,
              -0.9345344305038452,
              0.5715861320495605,
              -0.517876148223877,
              0.4325488209724426,
              -0.5225116610527039,
              0.2294730842113495,
              -0.29332542419433594,
              1.4930191040039062,
              0.20191335678100586,
              0.06339395046234131,
              -0.8630067110061646,
              -0.4055565893650055,
              1.283291220664978,
              1.2583506107330322,
              -1.0307952165603638,
              -1.0796175003051758,
              -0.005660302937030792,
              -0.3026241064071655,
              -0.42089661955833435,
              0.2756170630455017,
              -0.8075771331787109,
              -0.8117283582687378,
              -0.2307356297969818,
              -0.4942043125629425,
              -1.1039083003997803,
              1.236538290977478,
              -0.5735493302345276,
              -0.6888982653617859,
              0.16266217827796936,
              -0.6874724626541138,
              1.169924259185791,
              -0.2184915542602539,
              0.31304794549942017,
              0.5169081091880798,
              0.9932178258895874,
              -0.17399895191192627,
              0.060566484928131104,
              -0.05606124550104141,
              -0.15554611384868622,
              -0.7588722109794617,
              0.8253175020217896,
              0.3706430196762085,
              0.32575076818466187,
              -0.2899280786514282,
              -1.4988551139831543,
              -0.2508699297904968,
              -0.49109241366386414,
              -0.1899966597557068,
              -0.2825416624546051,
              0.7535319328308105,
              1.5006171464920044,
              -0.4885074496269226,
              0.9721674919128418,
              0.129302978515625,
              0.5406212210655212,
              -1.036348819732666,
              -0.6927956342697144,
              -0.915047824382782,
              -0.37214991450309753,
              -0.719666063785553,
              -0.34084659814834595,
              0.025622501969337463,
              1.516902208328247,
              -0.11366254091262817,
              -0.1293836534023285,
              -0.4358983039855957,
              0.8788203001022339,
              -1.0164110660552979,
              -0.002903580665588379,
              -0.8069247603416443,
              0.3148723244667053,
              0.17869886755943298,
              0.40456831455230713,
              -0.3473779857158661,
              -1.2967467308044434,
              1.1127665042877197,
              0.972009539604187,
              0.18289506435394287,
              1.6633230447769165,
              0.7461077570915222,
              0.5575858950614929,
              0.9826512932777405,
              0.3378932476043701,
              0.8871616721153259,
              -0.2932049632072449,
              0.08786389231681824,
              0.319000780582428,
              0.7508746981620789,
              1.040123701095581,
              -0.14301498234272003,
              0.4140048027038574,
              -0.4061390161514282,
              -0.15741458535194397,
              0.23856423795223236,
              -0.026092082262039185,
              -0.731031060218811,
              -0.4945276975631714,
              0.204799085855484,
              -1.8118300437927246,
              0.11866198480129242,
              -0.4098764955997467,
              -1.321239948272705,
              0.41885316371917725,
              -0.14077168703079224,
              1.6924793720245361,
              0.06172633171081543,
              0.39586806297302246,
              0.4460594654083252,
              -0.14537522196769714,
              0.4245929718017578,
              -0.5734315514564514,
              0.58135986328125,
              1.039180040359497,
              0.2041945457458496,
              -0.7745007276535034,
              -0.018084466457366943,
              0.8961354494094849,
              -0.2499942183494568,
              -0.11782808601856232,
              -0.19962918758392334,
              -0.7439751625061035,
              0.38578835129737854,
              -0.26452481746673584,
              0.14091208577156067,
              -0.5843343734741211,
              0.3265976309776306,
              0.9214553833007812,
              0.5255436301231384,
              0.9820154905319214,
              -0.23835523426532745,
              0.2420089840888977,
              -0.09712211787700653,
              -1.3383541107177734,
              0.155170276761055,
              0.13503895699977875,
              -1.0548174381256104,
              -0.9445807933807373,
              -0.6331267356872559,
              0.6995774507522583,
              -0.2910701632499695,
              1.775974154472351,
              0.1814315766096115],
 'title': 'what are the long-term effects of using raid?',
 'title_urls.url': []}

In [85]:
filtered_data = dataset['train'].filter(lambda example: example["answers.score"] >= 50)

# print(len(filtered_data))
# print(filtered_data[0])

Filter:   0%|          | 0/125323 [00:00<?, ? examples/s]

In [86]:
pprint(filtered_data[5])

{'answers.score': 184,
 'answers.text': 'that looks a lot like the phenomenon of [viscous '
                 'fingering](_url_0_), which can produce a fractal structure. '
                 'it occurs when a low-viscosity fluid (i guess air in this '
                 'case) infiltrates a high-viscosity fluid (latex). if that is '
                 'the case then the magnetic field has no effect on the '
                 'pattern formation.',
 'answers_urls.url': ['http://en.wikipedia.org/wiki/Viscous_fingering',
                      'http://en.wikipedia.org/wiki/Diffusion-limited_aggregation',
                      'https://i.minus.com/i9v8okHY3ZF6E.JPG',
                      'https://i.minus.com/ibieGENB9Gs0tB.JPG',
                      'http://en.wikipedia.org/wiki/Thermal_grease',
                      'http://www.youtube.com/watch?v=iZD1DRDgxN4&amp;feature=g-upl'],
 'selftext': 'so, i got a marker board that has a square magnet on the back, '
             'and i wanted to stick it to a mirror. obviously mirrors are not '
             'magnetic, so i put it on with liquid latex (makeup artist here). '
             'i let go of the marker board before it dried all the way, and it '
             'fell off with the latex on the magnet looking like this: _url_0_ '
             'why did it form amazing fractals like that? does the magnetic '
             'field have anything to do with the formation?',
 'selftext_urls.url': ['http://i.imgur.com/5y6H8.jpg'],
 'sent_vec': [-0.7400028705596924,
              -0.35396504402160645,
              0.7799546718597412,
              -0.42410942912101746,
              -0.7126046419143677,
              -0.7884789109230042,
              -0.15255391597747803,
              0.6933671832084656,
              0.20519019663333893,
              -0.35431402921676636,
              0.3254719078540802,
              0.13255980610847473,
              -0.2823876142501831,
              0.28339463472366333,
              0.8574087619781494,
              0.09011656045913696,
              -1.3471362590789795,
              -0.39331188797950745,
              0.015636995434761047,
              0.2874792218208313,
              0.674333930015564,
              0.14560961723327637,
              -0.24721096456050873,
              -0.5657639503479004,
              -0.8626523613929749,
              -0.09793980419635773,
              1.1407947540283203,
              -0.6707198023796082,
              0.6238455176353455,
              -0.0323357880115509,
              0.5176443457603455,
              1.0469719171524048,
              -0.7603831887245178,
              0.16632068157196045,
              -0.046848662197589874,
              -0.08837791532278061,
              -0.05899684131145477,
              -0.18660488724708557,
              -0.17870675027370453,
              0.2122131884098053,
              -0.4457278847694397,
              -0.08256158232688904,
              -0.19973082840442657,
              -0.09030312299728394,
              0.5878893136978149,
              0.4627390503883362,
              0.8726003170013428,
              0.029932931065559387,
              -0.13878487050533295,
              -0.0683184266090393,
              -0.3157053291797638,
              -0.8902754783630371,
              -0.3525153696537018,
              0.3151673376560211,
              0.23781156539916992,
              0.33602291345596313,
              -0.32217103242874146,
              -0.595209002494812,
              -0.17391400039196014,
              -0.011421158909797668,
              -0.30975615978240967,
              -0.19302698969841003,
              0.11501026153564453,
              0.5150982737541199,
              1.4884765148162842,
              -0.2822500765323639,
              1.0551865100860596,
              -0.2447640597820282,
              0.06858415901660919,
              0.04885855317115784,
              0.3460209369659424,
              0.7351697683334351,
              0.10062474757432938,
              1.4631829261779785,
              1.157137155532837,
              0.5284405946731567,
              -0.8531776666641235,
              0.5601586103439331,
              0.4714069366455078,
              0.1825740933418274,
              -0.14932295680046082,
              0.0320858359336853,
              -0.03087979555130005,
              0.11889968067407608,
              -0.3883800208568573,
              0.7940492630004883,
              0.04491500183939934,
              -0.33995258808135986,
              -0.6466920375823975,
              0.6429275274276733,
              -1.1504294872283936,
              0.16709809005260468,
              -1.5118756294250488,
              0.775160551071167,
              1.2402833700180054,
              0.548462986946106,
              0.23734858632087708,
              -0.3944293260574341,
              0.400218665599823,
              -0.4606800377368927,
              -0.4935833513736725,
              -0.13496355712413788,
              -0.2697710394859314,
              0.27686208486557007,
              0.22495709359645844,
              0.9706433415412903,
              0.2587268650531769,
              0.03222014755010605,
              -0.424905002117157,
              -0.5170336961746216,
              0.32233500480651855,
              0.04364472255110741,
              0.609164297580719,
              -0.6890343427658081,
              -0.2433629184961319,
              -0.46640339493751526,
              1.3464218378067017,
              0.07842403650283813,
              -0.20547804236412048,
              0.3389572501182556,
              -0.13766074180603027,
              -0.4468053877353668,
              -0.5344861149787903,
              -0.15647757053375244,
              -0.31728053092956543,
              -0.03206871077418327,
              0.030286304652690887,
              0.1281764805316925,
              -0.49766337871551514,
              -0.00045228004455566406,
              0.22083745896816254,
              -0.7686209082603455,
              0.450414776802063,
              0.6010016202926636,
              0.8692599534988403,
              -0.5187938213348389,
              -0.733091413974762,
              -0.19278846681118011,
              -0.8007953763008118,
              -0.12200769782066345,
              -0.5628440380096436,
              -0.08487994968891144,
              -0.20494899153709412,
              -0.8660917282104492,
              1.000447154045105,
              0.1049608588218689,
              -0.813892126083374,
              -0.12778079509735107,
              -0.09313364326953888,
              0.08842558413743973,
              -0.42548832297325134,
              -0.383185476064682,
              -0.6772949695587158,
              0.28136998414993286,
              -0.20585015416145325,
              0.14700432121753693,
              -0.16080915927886963,
              -0.09583064913749695,
              0.5061291456222534,
              -0.13797308504581451,
              -0.18939143419265747,
              0.6456750631332397,
              0.38744741678237915,
              0.21225708723068237,
              0.7198129892349243,
              0.13905063271522522,
              -0.992143452167511,
              -0.2977377474308014,
              -0.6315385103225708,
              -0.9182363748550415,
              -0.24454809725284576,
              0.8649427890777588,
              -0.7853448390960693,
              -0.30681347846984863,
              -0.8369288444519043,
              -0.27520623803138733,
              -0.6670874953269958,
              -0.46808427572250366,
              0.12311733514070511,
              0.7655738592147827,
              1.2736754417419434,
              0.3805849850177765,
              0.680777907371521,
              -0.6376879215240479,
              -1.1998579502105713,
              -0.3421263098716736,
              -0.152932807803154,
              -0.16690193116664886,
              0.010347861796617508,
              0.6634606719017029,
              -0.0027932971715927124,
              0.1305580586194992,
              0.15562506020069122,
              -0.014747697860002518,
              0.6681592464447021,
              -0.24928122758865356,
              -0.40180474519729614,
              -0.1460941582918167,
              0.45339956879615784,
              0.7412772178649902,
              -0.21001791954040527,
              -0.6687343120574951,
              -0.15597136318683624,
              0.24115300178527832,
              -0.0009395405650138855,
              0.19651386141777039,
              0.4511609673500061,
              0.1121600866317749,
              -0.7789426445960999,
              0.5529013872146606,
              0.5734128355979919,
              -1.3065325021743774,
              -0.5883365273475647,
              0.253131628036499,
              0.08737931400537491,
              0.24904094636440277,
              0.3733418881893158,
              -0.6001137495040894,
              -0.26596468687057495,
              -0.3570190966129303,
              0.19417989253997803,
              0.03344866633415222,
              -0.5418030619621277,
              -0.5460004210472107,
              0.11843644827604294,
              0.09115345031023026,
              -0.21158245205879211,
              0.5073163509368896,
              -0.6582810878753662,
              0.7272709012031555,
              0.7406650185585022,
              0.4153587222099304,
              -0.45169585943222046,
              -0.19489282369613647,
              1.6572651863098145,
              -0.5914297699928284,
              -0.8821333050727844,
              0.06708335876464844,
              -0.08070289343595505,
              -0.35352620482444763,
              -0.7610436677932739,
              0.5286676287651062,
              -0.030790597200393677,
              -0.44417738914489746,
              0.17639407515525818,
              -1.0946720838546753,
              -0.6733807325363159,
              0.153566375374794,
              -0.4311816096305847,
              0.33373311161994934,
              -0.6661574840545654,
              -0.17071735858917236,
              -0.706741213798523,
              1.1718612909317017,
              1.0819205045700073,
              0.27879369258880615,
              0.2772250771522522,
              -0.6874959468841553,
              -0.8135682344436646,
              0.7413111329078674,
              0.22493037581443787,
              0.15081287920475006,
              0.7152131795883179,
              -0.7642016410827637,
              -0.8244925141334534,
              -0.07854311168193817,
              -0.07202214002609253,
              0.41481709480285645,
              -0.600566565990448,
              0.5824743509292603,
              0.9082561731338501,
              -0.8416132926940918,
              0.6950708627700806,
              -0.02313685417175293,
              0.38134804368019104,
              0.18759113550186157,
              0.7016640901565552,
              -0.4254038333892822,
              -0.1868099421262741,
              0.6042658090591431,
              -0.5237427353858948,
              -0.8196717500686646,
              -0.21201668679714203,
              0.20357930660247803,
              0.1279677003622055,
              -0.3478532135486603,
              -0.07684670388698578,
              -1.2038280963897705,
              0.5757060050964355,
              -0.6319841742515564,
              -0.08572171628475189,
              0.5262293219566345,
              1.60321044921875,
              -0.5652333498001099,
              0.8125851154327393,
              0.697468638420105,
              -0.06936485320329666,
              0.13835659623146057,
              0.4345710873603821,
              -0.5455842018127441,
              0.27307796478271484,
              -0.07370003312826157,
              -1.419496774673462,
              1.1097381114959717,
              0.6664142608642578,
              0.04473790526390076,
              -0.139465793967247,
              0.08040758967399597,
              0.16189607977867126,
              -0.7369168996810913,
              0.12853926420211792,
              -0.696410596370697,
              -0.36046698689460754,
              0.3524669408798218,
              -0.5050281882286072,
              0.602116584777832,
              -0.39696890115737915,
              0.7833563089370728,
              0.17575708031654358,
              0.03194461762905121,
              -0.4690929055213928,
              -0.7055970430374146,
              0.7920684814453125,
              -0.49113011360168457,
              -0.01422175019979477,
              0.18530970811843872,
              -0.06670986860990524,
              0.1949770748615265,
              -0.5467003583908081,
              -0.07753944396972656,
              -0.31547975540161133,
              0.7885006070137024,
              -0.563673734664917,
              -0.5929857492446899,
              0.6925560235977173,
              0.032846882939338684,
              -0.39255133271217346,
              0.15395022928714752,
              -0.10820566117763519,
              -0.31153732538223267,
              0.1905362457036972,
              -0.1655278205871582,
              0.8046857118606567,
              -0.14276935160160065,
              0.23127180337905884,
              -0.16614794731140137,
              0.343841552734375,
              -0.48678460717201233,
              -1.3030472993850708,
              0.36965906620025635,
              -0.5688527822494507,
              1.4393947124481201,
              -0.022279247641563416,
              0.2854992151260376,
              0.008170224726200104,
              0.9566688537597656,
              -1.3328955173492432,
              -0.40043067932128906,
              -0.23423181474208832,
              0.9904333353042603,
              0.1278694123029709,
              1.0386087894439697,
              0.11025356501340866,
              0.05324050784111023,
              0.3274325132369995,
              0.5573951005935669,
              -0.02384278178215027,
              0.3661917448043823,
              0.3928542733192444,
              1.1873698234558105,
              0.1604224443435669,
              1.3550423383712769,
              -0.2280644178390503,
              0.39324629306793213,
              -0.6720679998397827,
              0.0807829201221466,
              -0.11637940257787704,
              0.5085299611091614,
              -0.5789366960525513,
              -0.05671820044517517,
              -0.37865838408470154,
              0.46413394808769226,
              0.9532620906829834,
              -0.5492025017738342],
 'title': 'i put liquid latex on a magnet, stuck it to a mirror, and before it '
          'dried pulled it off. the result was fractals? (pic included)',
 'title_urls.url': []}

In [10]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/mattan/Library/Python/3.9/lib/python/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Python/3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas

In [12]:
import csv

In [87]:
df = pandas.DataFrame(filtered_data)
display(df)

,title,selftext,answers.text,answers.score,title_urls.url,selftext_urls.url,answers_urls.url,sent_vec
0,how do centipedes/millipedes control all of th...,i always assumed creepy-crawlies were simpler ...,it's a distributed control system. each segmen...,4112,[],[],[https://en.wikipedia.org/wiki/Central_pattern...,"[-0.4820733666419983, -0.8969739079475403, -1...."
1,what is the significance of the derivative of ...,the derivative of the area of a circle is the ...,"so a derivative is a rate of change, right? so...",94,[],[],[http://www.reddit.com/r/askscience/comments/2...,"[-0.8882584571838379, -1.0788836479187012, -0...."
2,do we live in a cause-and-effect universe? are...,is there a 'root cause' to things? if you look...,you just heard a ping. why? because a ping-sha...,62,[],[],[],"[-0.4694886803627014, 0.41589224338531494, 0.6..."
3,how closely related any two people on average?,,you probably have no idea how complicated of a...,1601,[],[],"[http://en.wikipedia.org/wiki/Alleles, http://...","[-12.002178192138672, 5.419971942901611, -5.18..."
4,do primates ever keep the tools they fashion? ...,i was just thinking of what the real differenc...,okay i managed to find a source. i was reasona...,362,[],[],[http://www.wbur.org/npr/150734375/following-t...,"[-2.1536591053009033, -0.4547109603881836, 1.2..."
...,...,...,...,...,...,...,...,...
9766,why do atoms prefer to have 8 valence electrons?,so i understand that the p and s suborbitals c...,my attempt at a high-school-level explanation....,283,[],[],[http://en.wikipedia.org/wiki/Spherical_harmon...,"[-2.6905994415283203, 0.9548231959342957, -2.0..."
9767,does the use of microwave ovens distort chemic...,,"yes, microwave ovens distort chemical structur...",11385,[],[],"[http://docdro.id/5RPiQ9c, https://www.youtube...","[-0.6828480958938599, -0.32600581645965576, -0..."
9768,how could the universe be a few light-years ac...,shouldn't the universe be one light-second acr...,there is no speed limit on the rate of expansi...,1047,[],[],[http://m.youtube.com/#/watch?v=VNv0Yzk00qg&am...,"[0.12889410555362701, 0.7120699882507324, 0.69..."
9769,if our universe is expanding at certain rate w...,consider this as a follow-up question to /r/as...,good question. here's an analogy. imagine you ...,581,[],[],[http://www.nat.vu.nl/~wimu/Varying-Constants-...,"[1.50416898727417, 2.8521416187286377, 1.76644..."
9770,why does cyanide kill you so quickly?,hitler and many other german officials committ...,"cyanide can be ingested, inhaled, or absorbed ...",51,[],[],[http://en.wikipedia.org/wiki/Death_of_Adolf_H...,"[-0.8177230954170227, 0.31309056282043457, -0...."

In [88]:
blacklist = ["askscience", "megathread", "[", "x-post", "included", "/r/", "xpost", "reddit"]

mask = ~df['title'].apply(lambda x: any(keyword in x for keyword in blacklist))
df = df[mask]

mask = df['title'].apply(lambda x: x.endswith('?'))
df = df[mask]



mask = ~df['title_urls.url'].apply(lambda x: len(x) > 0)
df = df[mask]
df = df.reset_index()


# df_filtered['title'] = df_filtered['title'].map(lambda x: x.strip('"').replace('""', '"'))
display(df)

df['title'].to_csv(f'{wd}/ask_science.csv', quoting=csv.QUOTE_NONE, sep="\t")

,index,title,selftext,answers.text,answers.score,title_urls.url,selftext_urls.url,answers_urls.url,sent_vec
0,0,how do centipedes/millipedes control all of th...,i always assumed creepy-crawlies were simpler ...,it's a distributed control system. each segmen...,4112,[],[],[https://en.wikipedia.org/wiki/Central_pattern...,"[-0.4820733666419983, -0.8969739079475403, -1...."
1,1,what is the significance of the derivative of ...,the derivative of the area of a circle is the ...,"so a derivative is a rate of change, right? so...",94,[],[],[http://www.reddit.com/r/askscience/comments/2...,"[-0.8882584571838379, -1.0788836479187012, -0...."
2,2,do we live in a cause-and-effect universe? are...,is there a 'root cause' to things? if you look...,you just heard a ping. why? because a ping-sha...,62,[],[],[],"[-0.4694886803627014, 0.41589224338531494, 0.6..."
3,3,how closely related any two people on average?,,you probably have no idea how complicated of a...,1601,[],[],"[http://en.wikipedia.org/wiki/Alleles, http://...","[-12.002178192138672, 5.419971942901611, -5.18..."
4,4,do primates ever keep the tools they fashion? ...,i was just thinking of what the real differenc...,okay i managed to find a source. i was reasona...,362,[],[],[http://www.wbur.org/npr/150734375/following-t...,"[-2.1536591053009033, -0.4547109603881836, 1.2..."
...,...,...,...,...,...,...,...,...,...
9308,9766,why do atoms prefer to have 8 valence electrons?,so i understand that the p and s suborbitals c...,my attempt at a high-school-level explanation....,283,[],[],[http://en.wikipedia.org/wiki/Spherical_harmon...,"[-2.6905994415283203, 0.9548231959342957, -2.0..."
9309,9767,does the use of microwave ovens distort chemic...,,"yes, microwave ovens distort chemical structur...",11385,[],[],"[http://docdro.id/5RPiQ9c, https://www.youtube...","[-0.6828480958938599, -0.32600581645965576, -0..."
9310,9768,how could the universe be a few light-years ac...,shouldn't the universe be one light-second acr...,there is no speed limit on the rate of expansi...,1047,[],[],[http://m.youtube.com/#/watch?v=VNv0Yzk00qg&am...,"[0.12889410555362701, 0.7120699882507324, 0.69..."
9311,9769,if our universe is expanding at certain rate w...,consider this as a follow-up question to /r/as...,good question. here's an analogy. imagine you ...,581,[],[],[http://www.nat.vu.nl/~wimu/Varying-Constants-...,"[1.50416898727417, 2.8521416187286377, 1.76644..."
9312,9770,why does cyanide kill you so quickly?,hitler and many other german officials committ...,"cyanide can be ingested, inhaled, or absorbed ...",51,[],[],[http://en.wikipedia.org/wiki/Death_of_Adolf_H...,"[-0.8177230954170227, 0.31309056282043457, -0...."

In [89]:
df2 = pandas.DataFrame( dataset['train'].filter(lambda example: example["answers.score"] >= 100))
len(df2)

6304