In [73]:
parent_dir = "/Users/mattan"
project_path = "/thesis/SFT/data"
wd = f"{parent_dir}{project_path}"

In [5]:
import csv

import pandas
%pip install datasets

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets in /Users/mattan/Library/Python/3.9/lib/python/site-packages (2.20.0)
Requirement already satisfied: filelock in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (3.15.4)
Requirement already satisfied: numpy>=1.17 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (2.0.0)
Requirement already satisfied: pyarrow>=15.0.0 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (16.1.0)
Requirement already satisfied: pyarrow-hotfix in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /Library/Python/3.9/site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (4.66.4)
Requirement already satisfied: xxhash in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (3.4.1)
Requirement already satisfied: multiprocess in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.5.0,>=2023.1.0 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from fsspec[http]<=2024.5.0,>=2023.1.0->datasets) (2024.5.0)
Requirement already satisfied: aiohttp in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (3.9.5)
Requirement already satisfied: huggingface-hub>=0.21.2 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (0.23.4)
Requirement already satisfied: packaging in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from datasets) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /Library/Python/3.9/site-packages (from datasets) (6.0.1)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /Library/Python/3.9/site-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from huggingface-hub>=0.21.2->datasets) (4.8.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Python/3.9/site-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Python/3.9/site-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Python/3.9/site-packages (from requests>=2.32.2->datasets) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/3.9/site-packages (from requests>=2.32.2->datasets) (2024.7.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Python/3.9/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
from datasets import load_dataset

# Load the IMDB dataset
dataset = load_dataset('dhmeltzer/ask-science-qg')

# Print the first example in the training set
print(dataset['train'][0])

# Display dataset information
print(dataset)

/Library/Python/3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

{'title': 'what are the long-term effects of using raid?', 'selftext': "i'm talking about the one you plug into the wall. when it kills insects, it surely can't be good for my lungs and brain, or are the doses simply low enough not to be harmful? what are the long-term effects, then?", 'answers.text': "i did some research as a layman. one forum user [claims it contains](_url_1_) 300mg of transfluthrin, but i can't seem to find any sc johnson or raid site that corroborates that. transfluthrin is a pyrethroid, related to a pesticide produced by chrysanthemums called pyrethrum. the epa has [scant information on pyrethroids](_url_0_), but the consensus seems to be that low doses are mostly harmless.", 'answers.score': 3, 'title_urls.url': [], 'selftext_urls.url': [], 'answers_urls.url': ['http://www.epa.gov/pesticides/health/mosquitoes/pyrethroids4mosquitoes.htm', 'http://www.shanghaiexpat.com/phpbbforum/raid-plug-ins-is-it-deet-free-t112291.html'], 'sent_vec': [-0.7255505919456482, -0.003705620765686035, -0.6605789661407471, -0.9549583196640015, 1.1785768270492554, -0.45838603377342224, 0.8508591651916504, 1.0482252836227417, -0.6155848503112793, -0.7686198949813843, 0.7310305237770081, 0.07271027565002441, 0.07995486259460449, 0.5615687370300293, 0.6900725364685059, -0.2412843406200409, 0.7364736795425415, -1.1228086948394775, 0.4777783155441284, 0.3262585997581482, -0.28374895453453064, 1.6175569295883179, 0.5955187678337097, 0.511100709438324, -0.4910006821155548, -0.5436519384384155, -0.46288421750068665, 0.29690566658973694, -0.3154555857181549, -0.05731221288442612, -0.4832935333251953, 1.3867132663726807, -1.3953311443328857, -0.3483455181121826, -0.04913189262151718, -1.0132771730422974, -0.9409132599830627, 0.17989444732666016, 0.6255019903182983, 0.5489581823348999, -0.12876707315444946, 0.10089732706546783, -0.9448466300964355, 0.6149706840515137, -1.044508457183838, -0.07357308268547058, -0.3839132785797119, 0.3307129740715027, -0.5531113743782043, -0.39855897426605225, 1.0696812868118286, 0.03925669193267822, -0.5077837705612183, 1.1558656692504883, 1.0973191261291504, -1.9675004482269287, -1.2809333801269531, -0.556003212928772, -0.9620449542999268, -0.04009220004081726, -0.13174094259738922, 0.55538010597229, -1.4998594522476196, 0.2856186330318451, 0.10843431949615479, 1.0627423524856567, 0.23773087561130524, -0.6967437267303467, 1.5735468864440918, 0.22677290439605713, -0.36878782510757446, -0.004685729742050171, -0.47404274344444275, 1.0222598314285278, -0.7861779928207397, 0.25309330224990845, 0.09508755058050156, 0.49353641271591187, -0.1857030689716339, -0.5728816390037537, -0.8602582812309265, 0.4126831293106079, 0.9174937009811401, 0.5321619510650635, -0.049978017807006836, -0.17230930924415588, 0.46385669708251953, 1.4912497997283936, 0.0431763231754303, 0.1130569577217102, -0.6982657313346863, 1.486598014831543, -0.1624392569065094, 0.22989535331726074, -0.7062329053878784, 1.2650094032287598, 1.0528123378753662, -0.019090518355369568, -1.0171035528182983, 1.544553518295288, -1.0498337745666504, -0.9684882164001465, -1.774916172027588, -0.2391199767589569, 0.38392335176467896, -0.39982569217681885, 0.5450271368026733, 0.6820834875106812, 0.33199939131736755, 0.09752773493528366, -0.3643844723701477, 0.685961127281189, 0.1815194934606552, 0.1393355131149292, 0.10843540728092194, -0.5409760475158691, 0.039575427770614624, -0.02513578161597252, -0.7105093002319336, -0.6671932935714722, 0.3639281690120697, 0.9283304810523987, 0.7147669792175293, 0.36802101135253906, 0.9606180191040039, 0.7804251313209534, 0.771672248840332, 0.6587181091308594, 0.37913942337036133, 1.3706798553466797, 0.5260310173034668, -0.7236979603767395, 0.593049168586731, 0.40479961037635803, -0.25152894854545593, -0.30709290504455566, -0.13005799055099487, 0.2160225212574005, -0.5377644896507263, 0.6441632509231567, -0.9947337508201599, 0.7194046974182129, -0.5567602515220642, 0.9959844350814819, -0.3712312579154968, 1.4540071487426758, 0.30231890082359314, -0.7804475426673889, -0.7243222594261169, 1.013242244720459, -0.19760018587112427, 0.4542786180973053, -0.582022488117218, 0.7454156279563904, -0.7555918097496033, -0.03820929676294327, 0.8141480088233948, 0.31329262256622314, 1.4190175533294678, -0.18580983579158783, -0.48220139741897583, 0.13230927288532257, 0.2426493614912033, 0.5191774964332581, -0.9579929709434509, -0.19316864013671875, -1.180626630783081, -0.12745019793510437, -0.048479124903678894, 0.30163267254829407, -0.23744255304336548, -0.6422297358512878, 0.5607903003692627, -1.395583152770996, -1.3366379737854004, -0.5036786198616028, -0.42485207319259644, 1.0372644662857056, 0.551257848739624, 0.5196108222007751, -0.07189829647541046, 1.1568917036056519, -0.9827945232391357, 0.46226435899734497, -0.5082601308822632, 0.07237215340137482, 0.17064978182315826, -0.38607603311538696, -0.5900638103485107, -0.355351984500885, -2.4060821533203125, -0.6815676689147949, 0.9545533657073975, -0.12066520750522614, -0.627246618270874, -0.3880288004875183, -0.5698925852775574, -0.014936506748199463, 0.9166005849838257, -0.5042012333869934, 0.4813970923423767, -0.5081249475479126, 1.023249626159668, -0.9907490015029907, 0.41090309619903564, 0.5907599329948425, 0.4864232838153839, -1.3991103172302246, -0.8129428625106812, -1.0332105159759521, -0.5704267024993896, -0.5741279125213623, -1.7385622262954712, -0.8339242935180664, 0.8492460250854492, 0.9486119151115417, 0.04426000267267227, -0.5721083879470825, 0.3232623338699341, 0.032965660095214844, -1.3335102796554565, -0.36717405915260315, -0.8026113510131836, -1.3768982887268066, -1.0784833431243896, -0.3452392816543579, 0.6980811953544617, 0.9300453066825867, 0.003918876871466637, 1.1958903074264526, -0.23933537304401398, 0.08224919438362122, 1.0655677318572998, 0.6202654838562012, -0.055054664611816406, 0.5246956944465637, 0.7275998592376709, -0.8714204430580139, 0.012372240424156189, 0.7508845329284668, 0.039228588342666626, 0.5515520572662354, -0.9345344305038452, 0.5715861320495605, -0.517876148223877, 0.4325488209724426, -0.5225116610527039, 0.2294730842113495, -0.29332542419433594, 1.4930191040039062, 0.20191335678100586, 0.06339395046234131, -0.8630067110061646, -0.4055565893650055, 1.283291220664978, 1.2583506107330322, -1.0307952165603638, -1.0796175003051758, -0.005660302937030792, -0.3026241064071655, -0.42089661955833435, 0.2756170630455017, -0.8075771331787109, -0.8117283582687378, -0.2307356297969818, -0.4942043125629425, -1.1039083003997803, 1.236538290977478, -0.5735493302345276, -0.6888982653617859, 0.16266217827796936, -0.6874724626541138, 1.169924259185791, -0.2184915542602539, 0.31304794549942017, 0.5169081091880798, 0.9932178258895874, -0.17399895191192627, 0.060566484928131104, -0.05606124550104141, -0.15554611384868622, -0.7588722109794617, 0.8253175020217896, 0.3706430196762085, 0.32575076818466187, -0.2899280786514282, -1.4988551139831543, -0.2508699297904968, -0.49109241366386414, -0.1899966597557068, -0.2825416624546051, 0.7535319328308105, 1.5006171464920044, -0.4885074496269226, 0.9721674919128418, 0.129302978515625, 0.5406212210655212, -1.036348819732666, -0.6927956342697144, -0.915047824382782, -0.37214991450309753, -0.719666063785553, -0.34084659814834595, 0.025622501969337463, 1.516902208328247, -0.11366254091262817, -0.1293836534023285, -0.4358983039855957, 0.8788203001022339, -1.0164110660552979, -0.002903580665588379, -0.8069247603416443, 0.3148723244667053, 0.17869886755943298, 0.40456831455230713, -0.3473779857158661, -1.2967467308044434, 1.1127665042877197, 0.972009539604187, 0.18289506435394287, 1.6633230447769165, 0.7461077570915222, 0.5575858950614929, 0.9826512932777405, 0.3378932476043701, 0.8871616721153259, -0.2932049632072449, 0.08786389231681824, 0.319000780582428, 0.7508746981620789, 1.040123701095581, -0.14301498234272003, 0.4140048027038574, -0.4061390161514282, -0.15741458535194397, 0.23856423795223236, -0.026092082262039185, -0.731031060218811, -0.4945276975631714, 0.204799085855484, -1.8118300437927246, 0.11866198480129242, -0.4098764955997467, -1.321239948272705, 0.41885316371917725, -0.14077168703079224, 1.6924793720245361, 0.06172633171081543, 0.39586806297302246, 0.4460594654083252, -0.14537522196769714, 0.4245929718017578, -0.5734315514564514, 0.58135986328125, 1.039180040359497, 0.2041945457458496, -0.7745007276535034, -0.018084466457366943, 0.8961354494094849, -0.2499942183494568, -0.11782808601856232, -0.19962918758392334, -0.7439751625061035, 0.38578835129737854, -0.26452481746673584, 0.14091208577156067, -0.5843343734741211, 0.3265976309776306, 0.9214553833007812, 0.5255436301231384, 0.9820154905319214, -0.23835523426532745, 0.2420089840888977, -0.09712211787700653, -1.3383541107177734, 0.155170276761055, 0.13503895699977875, -1.0548174381256104, -0.9445807933807373, -0.6331267356872559, 0.6995774507522583, -0.2910701632499695, 1.775974154472351, 0.1814315766096115]}
DatasetDict({
    train: Dataset({
        features: ['title', 'selftext', 'answers.text', 'answers.score', 'title_urls.url', 'selftext_urls.url', 'answers_urls.url', 'sent_vec'],
        num_rows: 125323
    })
    validation: Dataset({
        features: ['title', 'selftext', 'answers.text', 'answers.score', 'title_urls.url', 'selftext_urls.url', 'answers_urls.url', 'sent_vec'],
        num_rows: 2060
    })
    test: Dataset({
        features: ['title', 'selftext', 'answers.text', 'answers.score', 'title_urls.url', 'selftext_urls.url', 'answers_urls.url', 'sent_vec'],
        num_rows: 4058
    })
})

In [7]:
from pprint import pprint

In [8]:
pprint(dataset['train'][0])

{'answers.score': 3,
 'answers.text': 'i did some research as a layman. one forum user [claims it '
                 "contains](_url_1_) 300mg of transfluthrin, but i can't seem "
                 'to find any sc johnson or raid site that corroborates that. '
                 'transfluthrin is a pyrethroid, related to a pesticide '
                 'produced by chrysanthemums called pyrethrum. the epa has '
                 '[scant information on pyrethroids](_url_0_), but the '
                 'consensus seems to be that low doses are mostly harmless.',
 'answers_urls.url': ['http://www.epa.gov/pesticides/health/mosquitoes/pyrethroids4mosquitoes.htm',
                      'http://www.shanghaiexpat.com/phpbbforum/raid-plug-ins-is-it-deet-free-t112291.html'],
 'selftext': "i'm talking about the one you plug into the wall. when it kills "
             "insects, it surely can't be good for my lungs and brain, or are "
             'the doses simply low enough not to be harmful? what are the '
             'long-term effects, then?',
 'selftext_urls.url': [],
 'sent_vec': [-0.7255505919456482,
              -0.003705620765686035,
              -0.6605789661407471,
              -0.9549583196640015,
              1.1785768270492554,
              -0.45838603377342224,
              0.8508591651916504,
              1.0482252836227417,
              -0.6155848503112793,
              -0.7686198949813843,
              0.7310305237770081,
              0.07271027565002441,
              0.07995486259460449,
              0.5615687370300293,
              0.6900725364685059,
              -0.2412843406200409,
              0.7364736795425415,
              -1.1228086948394775,
              0.4777783155441284,
              0.3262585997581482,
              -0.28374895453453064,
              1.6175569295883179,
              0.5955187678337097,
              0.511100709438324,
              -0.4910006821155548,
              -0.5436519384384155,
              -0.46288421750068665,
              0.29690566658973694,
              -0.3154555857181549,
              -0.05731221288442612,
              -0.4832935333251953,
              1.3867132663726807,
              -1.3953311443328857,
              -0.3483455181121826,
              -0.04913189262151718,
              -1.0132771730422974,
              -0.9409132599830627,
              0.17989444732666016,
              0.6255019903182983,
              0.5489581823348999,
              -0.12876707315444946,
              0.10089732706546783,
              -0.9448466300964355,
              0.6149706840515137,
              -1.044508457183838,
              -0.07357308268547058,
              -0.3839132785797119,
              0.3307129740715027,
              -0.5531113743782043,
              -0.39855897426605225,
              1.0696812868118286,
              0.03925669193267822,
              -0.5077837705612183,
              1.1558656692504883,
              1.0973191261291504,
              -1.9675004482269287,
              -1.2809333801269531,
              -0.556003212928772,
              -0.9620449542999268,
              -0.04009220004081726,
              -0.13174094259738922,
              0.55538010597229,
              -1.4998594522476196,
              0.2856186330318451,
              0.10843431949615479,
              1.0627423524856567,
              0.23773087561130524,
              -0.6967437267303467,
              1.5735468864440918,
              0.22677290439605713,
              -0.36878782510757446,
              -0.004685729742050171,
              -0.47404274344444275,
              1.0222598314285278,
              -0.7861779928207397,
              0.25309330224990845,
              0.09508755058050156,
              0.49353641271591187,
              -0.1857030689716339,
              -0.5728816390037537,
              -0.8602582812309265,
              0.4126831293106079,
              0.9174937009811401,
              0.5321619510650635,
              -0.049978017807006836,
              -0.17230930924415588,
              0.46385669708251953,
              1.4912497997283936,
              0.0431763231754303,
              0.1130569577217102,
              -0.6982657313346863,
              1.486598014831543,
              -0.1624392569065094,
              0.22989535331726074,
              -0.7062329053878784,
              1.2650094032287598,
              1.0528123378753662,
              -0.019090518355369568,
              -1.0171035528182983,
              1.544553518295288,
              -1.0498337745666504,
              -0.9684882164001465,
              -1.774916172027588,
              -0.2391199767589569,
              0.38392335176467896,
              -0.39982569217681885,
              0.5450271368026733,
              0.6820834875106812,
              0.33199939131736755,
              0.09752773493528366,
              -0.3643844723701477,
              0.685961127281189,
              0.1815194934606552,
              0.1393355131149292,
              0.10843540728092194,
              -0.5409760475158691,
              0.039575427770614624,
              -0.02513578161597252,
              -0.7105093002319336,
              -0.6671932935714722,
              0.3639281690120697,
              0.9283304810523987,
              0.7147669792175293,
              0.36802101135253906,
              0.9606180191040039,
              0.7804251313209534,
              0.771672248840332,
              0.6587181091308594,
              0.37913942337036133,
              1.3706798553466797,
              0.5260310173034668,
              -0.7236979603767395,
              0.593049168586731,
              0.40479961037635803,
              -0.25152894854545593,
              -0.30709290504455566,
              -0.13005799055099487,
              0.2160225212574005,
              -0.5377644896507263,
              0.6441632509231567,
              -0.9947337508201599,
              0.7194046974182129,
              -0.5567602515220642,
              0.9959844350814819,
              -0.3712312579154968,
              1.4540071487426758,
              0.30231890082359314,
              -0.7804475426673889,
              -0.7243222594261169,
              1.013242244720459,
              -0.19760018587112427,
              0.4542786180973053,
              -0.582022488117218,
              0.7454156279563904,
              -0.7555918097496033,
              -0.03820929676294327,
              0.8141480088233948,
              0.31329262256622314,
              1.4190175533294678,
              -0.18580983579158783,
              -0.48220139741897583,
              0.13230927288532257,
              0.2426493614912033,
              0.5191774964332581,
              -0.9579929709434509,
              -0.19316864013671875,
              -1.180626630783081,
              -0.12745019793510437,
              -0.048479124903678894,
              0.30163267254829407,
              -0.23744255304336548,
              -0.6422297358512878,
              0.5607903003692627,
              -1.395583152770996,
              -1.3366379737854004,
              -0.5036786198616028,
              -0.42485207319259644,
              1.0372644662857056,
              0.551257848739624,
              0.5196108222007751,
              -0.07189829647541046,
              1.1568917036056519,
              -0.9827945232391357,
              0.46226435899734497,
              -0.5082601308822632,
              0.07237215340137482,
              0.17064978182315826,
              -0.38607603311538696,
              -0.5900638103485107,
              -0.355351984500885,
              -2.4060821533203125,
              -0.6815676689147949,
              0.9545533657073975,
              -0.12066520750522614,
              -0.627246618270874,
              -0.3880288004875183,
              -0.5698925852775574,
              -0.014936506748199463,
              0.9166005849838257,
              -0.5042012333869934,
              0.4813970923423767,
              -0.5081249475479126,
              1.023249626159668,
              -0.9907490015029907,
              0.41090309619903564,
              0.5907599329948425,
              0.4864232838153839,
              -1.3991103172302246,
              -0.8129428625106812,
              -1.0332105159759521,
              -0.5704267024993896,
              -0.5741279125213623,
              -1.7385622262954712,
              -0.8339242935180664,
              0.8492460250854492,
              0.9486119151115417,
              0.04426000267267227,
              -0.5721083879470825,
              0.3232623338699341,
              0.032965660095214844,
              -1.3335102796554565,
              -0.36717405915260315,
              -0.8026113510131836,
              -1.3768982887268066,
              -1.0784833431243896,
              -0.3452392816543579,
              0.6980811953544617,
              0.9300453066825867,
              0.003918876871466637,
              1.1958903074264526,
              -0.23933537304401398,
              0.08224919438362122,
              1.0655677318572998,
              0.6202654838562012,
              -0.055054664611816406,
              0.5246956944465637,
              0.7275998592376709,
              -0.8714204430580139,
              0.012372240424156189,
              0.7508845329284668,
              0.039228588342666626,
              0.5515520572662354,
              -0.9345344305038452,
              0.5715861320495605,
              -0.517876148223877,
              0.4325488209724426,
              -0.5225116610527039,
              0.2294730842113495,
              -0.29332542419433594,
              1.4930191040039062,
              0.20191335678100586,
              0.06339395046234131,
              -0.8630067110061646,
              -0.4055565893650055,
              1.283291220664978,
              1.2583506107330322,
              -1.0307952165603638,
              -1.0796175003051758,
              -0.005660302937030792,
              -0.3026241064071655,
              -0.42089661955833435,
              0.2756170630455017,
              -0.8075771331787109,
              -0.8117283582687378,
              -0.2307356297969818,
              -0.4942043125629425,
              -1.1039083003997803,
              1.236538290977478,
              -0.5735493302345276,
              -0.6888982653617859,
              0.16266217827796936,
              -0.6874724626541138,
              1.169924259185791,
              -0.2184915542602539,
              0.31304794549942017,
              0.5169081091880798,
              0.9932178258895874,
              -0.17399895191192627,
              0.060566484928131104,
              -0.05606124550104141,
              -0.15554611384868622,
              -0.7588722109794617,
              0.8253175020217896,
              0.3706430196762085,
              0.32575076818466187,
              -0.2899280786514282,
              -1.4988551139831543,
              -0.2508699297904968,
              -0.49109241366386414,
              -0.1899966597557068,
              -0.2825416624546051,
              0.7535319328308105,
              1.5006171464920044,
              -0.4885074496269226,
              0.9721674919128418,
              0.129302978515625,
              0.5406212210655212,
              -1.036348819732666,
              -0.6927956342697144,
              -0.915047824382782,
              -0.37214991450309753,
              -0.719666063785553,
              -0.34084659814834595,
              0.025622501969337463,
              1.516902208328247,
              -0.11366254091262817,
              -0.1293836534023285,
              -0.4358983039855957,
              0.8788203001022339,
              -1.0164110660552979,
              -0.002903580665588379,
              -0.8069247603416443,
              0.3148723244667053,
              0.17869886755943298,
              0.40456831455230713,
              -0.3473779857158661,
              -1.2967467308044434,
              1.1127665042877197,
              0.972009539604187,
              0.18289506435394287,
              1.6633230447769165,
              0.7461077570915222,
              0.5575858950614929,
              0.9826512932777405,
              0.3378932476043701,
              0.8871616721153259,
              -0.2932049632072449,
              0.08786389231681824,
              0.319000780582428,
              0.7508746981620789,
              1.040123701095581,
              -0.14301498234272003,
              0.4140048027038574,
              -0.4061390161514282,
              -0.15741458535194397,
              0.23856423795223236,
              -0.026092082262039185,
              -0.731031060218811,
              -0.4945276975631714,
              0.204799085855484,
              -1.8118300437927246,
              0.11866198480129242,
              -0.4098764955997467,
              -1.321239948272705,
              0.41885316371917725,
              -0.14077168703079224,
              1.6924793720245361,
              0.06172633171081543,
              0.39586806297302246,
              0.4460594654083252,
              -0.14537522196769714,
              0.4245929718017578,
              -0.5734315514564514,
              0.58135986328125,
              1.039180040359497,
              0.2041945457458496,
              -0.7745007276535034,
              -0.018084466457366943,
              0.8961354494094849,
              -0.2499942183494568,
              -0.11782808601856232,
              -0.19962918758392334,
              -0.7439751625061035,
              0.38578835129737854,
              -0.26452481746673584,
              0.14091208577156067,
              -0.5843343734741211,
              0.3265976309776306,
              0.9214553833007812,
              0.5255436301231384,
              0.9820154905319214,
              -0.23835523426532745,
              0.2420089840888977,
              -0.09712211787700653,
              -1.3383541107177734,
              0.155170276761055,
              0.13503895699977875,
              -1.0548174381256104,
              -0.9445807933807373,
              -0.6331267356872559,
              0.6995774507522583,
              -0.2910701632499695,
              1.775974154472351,
              0.1814315766096115],
 'title': 'what are the long-term effects of using raid?',
 'title_urls.url': []}

In [9]:
filtered_data = dataset['train'].filter(lambda example: example["answers.score"] >= 100)

# print(len(filtered_data))
# print(filtered_data[0])

Filter:   0%|          | 0/125323 [00:00<?, ? examples/s]

In [14]:
pprint(filtered_data[5])

{'answers.score': 234,
 'answers.text': 'it might surprise you to know that the first under-sea '
                 "cables were laid in the mid-1800s - we've been doing this "
                 'for over 150 years now. and yes, they do have a life-span. '
                 'there\'s no "if" we ever need to replace them, we *do* '
                 'replace them regularly (as in every few decades). the cables '
                 'are subject to wear and other damage too - if they are '
                 'severed then they can be repaired in sections (but this '
                 'leaves a weak point in the system and is not desirable). but '
                 "otherwise there comes a point where repair wouldn't even be "
                 'practical, so you get our your ship and lay down a new '
                 'cable! nothing humans make tends to last indefinitely - '
                 'electrical wiring, gas and water pipes, roads, etc. all have '
                 'a life-span. we often use things way beyond what their '
                 "original rated life-span was, but there's not really "
                 'anything that we make under the assumption it will last '
                 "indefinitely. there's always an idea of when we'll need to "
                 "replace something at the point when it's first made.",
 'answers_urls.url': ['http://www.wikiwand.com/en/2008_submarine_cable_disruption',
                      'http://www.theguardian.com/technology/2014/aug/14/google-undersea-fibre-optic-cables-shark-attacks',
                      'http://www.aoml.noaa.gov/phod/floridacurrent/background.php'],
 'selftext': 'i mean there must be an estimate of if we ever need to replace '
             'them!',
 'selftext_urls.url': [],
 'sent_vec': [-3.6109015941619873,
              -0.026270315051078796,
              1.0701961517333984,
              -0.8384488224983215,
              0.18420718610286713,
              -1.4180511236190796,
              -1.4380050897598267,
              -0.06515005230903625,
              -0.21258068084716797,
              -0.17731690406799316,
              0.4865144193172455,
              3.7104804515838623,
              0.23320485651493073,
              -0.19341488182544708,
              -1.336180329322815,
              -0.04163175821304321,
              -3.196709632873535,
              -1.9488638639450073,
              -1.6687742471694946,
              1.565201759338379,
              -0.6092138290405273,
              0.19196102023124695,
              -1.235748052597046,
              0.08996143937110901,
              -0.519755482673645,
              1.1486214399337769,
              -0.5961313843727112,
              0.6646173000335693,
              -1.1270415782928467,
              -1.2405940294265747,
              -1.128928780555725,
              0.7482753992080688,
              -0.1740676313638687,
              -0.9250616431236267,
              0.9989631772041321,
              1.4996421337127686,
              0.45762258768081665,
              -0.5549222230911255,
              -0.3215608298778534,
              -2.278654098510742,
              -0.7213620543479919,
              -1.599220871925354,
              -0.8288974165916443,
              0.505635142326355,
              0.40656134486198425,
              1.9707447290420532,
              2.191133975982666,
              -1.8799153566360474,
              -0.6356673240661621,
              0.5690579414367676,
              -0.8456574082374573,
              1.6362723112106323,
              0.7961907386779785,
              0.2585301101207733,
              -0.37422072887420654,
              -0.8920275568962097,
              1.4669787883758545,
              -0.11118246614933014,
              0.06777369976043701,
              -0.6692632436752319,
              0.09556141495704651,
              -0.6131205558776855,
              -0.8191766738891602,
              1.1273062229156494,
              1.8681375980377197,
              -0.01975613832473755,
              1.450469732284546,
              -0.6972033381462097,
              -0.5268983840942383,
              2.6423468589782715,
              -0.5359458923339844,
              -1.512080430984497,
              -1.1405495405197144,
              0.6687278151512146,
              -0.14907638728618622,
              0.5047715902328491,
              1.0158079862594604,
              -0.7123591303825378,
              0.6294059753417969,
              0.3718106746673584,
              -2.6522586345672607,
              -2.1622352600097656,
              -0.4158739149570465,
              -0.4365679919719696,
              -0.608267068862915,
              0.5079038739204407,
              0.5693017840385437,
              0.20077422261238098,
              -0.5899597406387329,
              -0.04874858260154724,
              -0.24303513765335083,
              1.219309687614441,
              3.255876064300537,
              -0.09249995648860931,
              -0.7913856506347656,
              1.616765022277832,
              -1.3301267623901367,
              1.341639518737793,
              -1.0152136087417603,
              0.2686615586280823,
              -0.5771473050117493,
              0.6370606422424316,
              -2.7674365043640137,
              -1.007082462310791,
              0.3271391987800598,
              -0.8934340476989746,
              0.034743860363960266,
              1.1321355104446411,
              -0.03048432245850563,
              -1.1631455421447754,
              0.5271831750869751,
              -0.16479924321174622,
              0.7339484691619873,
              -0.5544584393501282,
              -0.5603448152542114,
              -0.5227979421615601,
              -0.22020892798900604,
              0.16139930486679077,
              -2.146270275115967,
              -0.9043426513671875,
              1.5756033658981323,
              -0.6566126346588135,
              -0.09430345892906189,
              -0.09890338778495789,
              -0.24335278570652008,
              -0.2990259826183319,
              0.9744052290916443,
              2.403254985809326,
              0.6424744129180908,
              1.1509240865707397,
              0.7041495442390442,
              -1.0382682085037231,
              -0.6706137657165527,
              0.886757493019104,
              -0.679024338722229,
              2.323904514312744,
              2.4586479663848877,
              -0.35993528366088867,
              0.35682833194732666,
              2.0256717205047607,
              0.47509366273880005,
              0.8072376251220703,
              2.9852547645568848,
              -1.0338084697723389,
              0.05365839600563049,
              -0.6923867464065552,
              1.3546415567398071,
              -0.624339759349823,
              0.4244881868362427,
              -1.796088695526123,
              0.9794532060623169,
              -2.4053585529327393,
              1.9422898292541504,
              -0.5428828001022339,
              -0.21494469046592712,
              -0.562771737575531,
              -1.785484790802002,
              0.5358019471168518,
              -0.9291450381278992,
              0.6613479852676392,
              -0.8135716915130615,
              1.9713985919952393,
              -1.4108633995056152,
              1.0603268146514893,
              1.0645711421966553,
              -0.013706892728805542,
              -1.1590551137924194,
              -0.7976004481315613,
              1.7586910724639893,
              0.4598078727722168,
              0.3601386249065399,
              1.3227866888046265,
              2.957514762878418,
              -2.0142855644226074,
              1.535920262336731,
              0.7361334562301636,
              -2.3289542198181152,
              0.26556089520454407,
              -1.0156376361846924,
              2.7585339546203613,
              -1.2959953546524048,
              -0.5420466661453247,
              -0.5049563050270081,
              -0.08831308782100677,
              0.8333266973495483,
              -1.4118187427520752,
              0.45371371507644653,
              -0.01702592708170414,
              -0.7801763415336609,
              -0.9740513563156128,
              0.2533402740955353,
              1.2774653434753418,
              1.1206539869308472,
              2.6276633739471436,
              0.6354463696479797,
              -0.1121826097369194,
              -2.0875635147094727,
              -0.5482932329177856,
              -0.7271172404289246,
              -2.317727565765381,
              -2.191068172454834,
              0.32098010182380676,
              -1.5208332538604736,
              0.6640550494194031,
              1.0326884984970093,
              -0.1718260645866394,
              1.1990092992782593,
              -1.075744390487671,
              -1.7354724407196045,
              -0.09904778003692627,
              0.4424823522567749,
              0.01801270991563797,
              2.8568427562713623,
              -0.9631747603416443,
              2.541985273361206,
              0.36781132221221924,
              -0.8796938061714172,
              0.07742604613304138,
              0.5997903347015381,
              -0.5826396346092224,
              1.611175298690796,
              -0.9516744613647461,
              3.381643772125244,
              -2.8783493041992188,
              0.04346729442477226,
              0.23203274607658386,
              -0.49963751435279846,
              1.7182772159576416,
              -0.049864090979099274,
              -0.5333600044250488,
              0.055769190192222595,
              0.9802634119987488,
              -0.6342160105705261,
              2.0814266204833984,
              -0.6381599307060242,
              -2.2924790382385254,
              -0.40115880966186523,
              -1.373314619064331,
              0.32179805636405945,
              0.08444243669509888,
              -1.1146022081375122,
              -1.5407416820526123,
              -0.5500466823577881,
              -1.9435704946517944,
              0.09663516283035278,
              2.263432502746582,
              -0.7271849513053894,
              0.9874046444892883,
              1.085669755935669,
              1.1898109912872314,
              -2.375408172607422,
              0.11737228184938431,
              -1.0583254098892212,
              2.193121910095215,
              -2.419179677963257,
              -0.6573259830474854,
              -0.8924859762191772,
              2.0493948459625244,
              -0.017788484692573547,
              0.45825621485710144,
              0.3021082878112793,
              1.5265233516693115,
              0.27609747648239136,
              -1.7521864175796509,
              1.2163355350494385,
              0.5374995470046997,
              -0.41151294112205505,
              1.3050071001052856,
              -1.9858180284500122,
              -2.21014404296875,
              -2.3800032138824463,
              -0.05618157982826233,
              -0.07991798222064972,
              1.5594013929367065,
              1.272183895111084,
              -0.10620344430208206,
              0.03259709104895592,
              -2.056278705596924,
              -0.8985913991928101,
              0.5373722314834595,
              -0.4906368553638458,
              -1.2238273620605469,
              -2.2513537406921387,
              1.5413389205932617,
              1.9197098016738892,
              -0.8323475122451782,
              0.35862553119659424,
              -1.574359655380249,
              1.3183352947235107,
              -0.7183160185813904,
              1.567695140838623,
              2.2623331546783447,
              -0.9704980254173279,
              -1.1145251989364624,
              2.3271212577819824,
              0.24912124872207642,
              -2.0343241691589355,
              -0.4602751135826111,
              0.275387704372406,
              0.22557833790779114,
              1.5139951705932617,
              -0.22521191835403442,
              -0.2585694491863251,
              0.9932056665420532,
              0.3510795533657074,
              0.18229562044143677,
              1.2082908153533936,
              1.98752760887146,
              1.7190890312194824,
              -1.4356409311294556,
              0.2079210877418518,
              -0.28334739804267883,
              0.7117346525192261,
              0.1543044149875641,
              0.01240154542028904,
              0.8423686027526855,
              -2.295427083969116,
              0.4515402317047119,
              -1.6435909271240234,
              0.13469871878623962,
              0.09571895003318787,
              1.8427019119262695,
              0.35508430004119873,
              0.9561909437179565,
              0.5964038968086243,
              0.3711696267127991,
              1.9346176385879517,
              0.848486602306366,
              -0.8917144536972046,
              0.018297061324119568,
              0.3706018626689911,
              2.0833263397216797,
              0.8482943177223206,
              0.6949381232261658,
              -0.36739981174468994,
              2.3306796550750732,
              -0.5891698598861694,
              -0.7430531978607178,
              -2.7504935264587402,
              0.809629499912262,
              -0.6193041801452637,
              0.5067757964134216,
              0.8049039840698242,
              2.1499295234680176,
              -0.4288162291049957,
              0.7483850121498108,
              1.0865437984466553,
              0.5651884078979492,
              0.19074782729148865,
              0.4289887845516205,
              -0.5587553977966309,
              -0.58362877368927,
              1.2922334671020508,
              1.8022369146347046,
              0.40219318866729736,
              -2.872537136077881,
              -0.1027226448059082,
              0.7291797399520874,
              0.4944252371788025,
              -1.5733251571655273,
              -1.6364741325378418,
              -0.42431503534317017,
              -0.6372535228729248,
              3.389984130859375,
              -0.9517613649368286,
              0.15241485834121704,
              -1.991528034210205,
              0.23103024065494537,
              -3.413017988204956,
              0.9189913868904114,
              2.7644667625427246,
              1.6038925647735596,
              0.6782437562942505,
              -1.5028738975524902,
              0.20957636833190918,
              -2.3404905796051025,
              -0.4966549873352051,
              2.1291887760162354,
              -2.0861501693725586,
              1.0448962450027466,
              -1.056191086769104,
              -0.568573534488678,
              3.322899341583252,
              -0.2535959482192993],
 'title': 'will the cables laying along the bottom of the sea ever deteriorate '
          'or even decompose?',
 'title_urls.url': []}

In [10]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/mattan/Library/Python/3.9/lib/python/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Python/3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/mattan/Library/Python/3.9/lib/python/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas

In [12]:
import csv

In [83]:
df = pandas.DataFrame(filtered_data)
display(df)

,title,selftext,answers.text,answers.score,title_urls.url,selftext_urls.url,answers_urls.url,sent_vec
0,how do centipedes/millipedes control all of th...,i always assumed creepy-crawlies were simpler ...,it's a distributed control system. each segmen...,4112,[],[],[https://en.wikipedia.org/wiki/Central_pattern...,"[-0.4820733666419983, -0.8969739079475403, -1...."
1,how closely related any two people on average?,,you probably have no idea how complicated of a...,1601,[],[],"[http://en.wikipedia.org/wiki/Alleles, http://...","[-12.002178192138672, 5.419971942901611, -5.18..."
2,do primates ever keep the tools they fashion? ...,i was just thinking of what the real differenc...,okay i managed to find a source. i was reasona...,362,[],[],[http://www.wbur.org/npr/150734375/following-t...,"[-2.1536591053009033, -0.4547109603881836, 1.2..."
3,"i put liquid latex on a magnet, stuck it to a ...","so, i got a marker board that has a square mag...",that looks a lot like the phenomenon of [visco...,184,[],[http://i.imgur.com/5y6H8.jpg],[http://en.wikipedia.org/wiki/Viscous_fingerin...,"[-0.7400028705596924, -0.35396504402160645, 0...."
4,could you tell that camels have humps just by ...,"like, say you had some archaeology students wh...","the short answer is ""probably not."" the long a...",214,[],[],[https://upload.wikimedia.org/wikipedia/common...,"[-1.878812551498413, 1.1259770393371582, 1.454..."
...,...,...,...,...,...,...,...,...
6299,how much oxygen does the new honda fuel cell v...,[removed],"and we can actually do the math as well, to sh...",379,[],[],[],"[-1.826596736907959, 0.057641178369522095, 0.1..."
6300,why do atoms prefer to have 8 valence electrons?,so i understand that the p and s suborbitals c...,my attempt at a high-school-level explanation....,283,[],[],[http://en.wikipedia.org/wiki/Spherical_harmon...,"[-2.6905994415283203, 0.9548231959342957, -2.0..."
6301,does the use of microwave ovens distort chemic...,,"yes, microwave ovens distort chemical structur...",11385,[],[],"[http://docdro.id/5RPiQ9c, https://www.youtube...","[-0.6828480958938599, -0.32600581645965576, -0..."
6302,how could the universe be a few light-years ac...,shouldn't the universe be one light-second acr...,there is no speed limit on the rate of expansi...,1047,[],[],[http://m.youtube.com/#/watch?v=VNv0Yzk00qg&am...,"[0.12889410555362701, 0.7120699882507324, 0.69..."
6303,if our universe is expanding at certain rate w...,consider this as a follow-up question to /r/as...,good question. here's an analogy. imagine you ...,581,[],[],[http://www.nat.vu.nl/~wimu/Varying-Constants-...,"[1.50416898727417, 2.8521416187286377, 1.76644..."

In [84]:
blacklist = ["askscience", "megathread", "[", "x-post", "included", "/r/", "xpost", "reddit"]

mask = ~df['title'].apply(lambda x: any(keyword in x for keyword in blacklist))
df = df[mask]

mask = df['title'].apply(lambda x: x.endswith('?'))
df = df[mask]



mask = ~df['title_urls.url'].apply(lambda x: len(x) > 0)
df = df[mask]
df = df.reset_index()


# df_filtered['title'] = df_filtered['title'].map(lambda x: x.strip('"').replace('""', '"'))
display(df)

df['title'].to_csv(f'{wd}/ask_science.csv', quoting=csv.QUOTE_NONE, sep="\t")

,index,title,selftext,answers.text,answers.score,title_urls.url,selftext_urls.url,answers_urls.url,sent_vec
0,0,how do centipedes/millipedes control all of th...,i always assumed creepy-crawlies were simpler ...,it's a distributed control system. each segmen...,4112,[],[],[https://en.wikipedia.org/wiki/Central_pattern...,"[-0.4820733666419983, -0.8969739079475403, -1...."
1,1,how closely related any two people on average?,,you probably have no idea how complicated of a...,1601,[],[],"[http://en.wikipedia.org/wiki/Alleles, http://...","[-12.002178192138672, 5.419971942901611, -5.18..."
2,2,do primates ever keep the tools they fashion? ...,i was just thinking of what the real differenc...,okay i managed to find a source. i was reasona...,362,[],[],[http://www.wbur.org/npr/150734375/following-t...,"[-2.1536591053009033, -0.4547109603881836, 1.2..."
3,4,could you tell that camels have humps just by ...,"like, say you had some archaeology students wh...","the short answer is ""probably not."" the long a...",214,[],[],[https://upload.wikimedia.org/wikipedia/common...,"[-1.878812551498413, 1.1259770393371582, 1.454..."
4,5,will the cables laying along the bottom of the...,i mean there must be an estimate of if we ever...,it might surprise you to know that the first u...,234,[],[],[http://www.wikiwand.com/en/2008_submarine_cab...,"[-3.6109015941619873, -0.026270315051078796, 1..."
...,...,...,...,...,...,...,...,...,...
6012,6299,how much oxygen does the new honda fuel cell v...,[removed],"and we can actually do the math as well, to sh...",379,[],[],[],"[-1.826596736907959, 0.057641178369522095, 0.1..."
6013,6300,why do atoms prefer to have 8 valence electrons?,so i understand that the p and s suborbitals c...,my attempt at a high-school-level explanation....,283,[],[],[http://en.wikipedia.org/wiki/Spherical_harmon...,"[-2.6905994415283203, 0.9548231959342957, -2.0..."
6014,6301,does the use of microwave ovens distort chemic...,,"yes, microwave ovens distort chemical structur...",11385,[],[],"[http://docdro.id/5RPiQ9c, https://www.youtube...","[-0.6828480958938599, -0.32600581645965576, -0..."
6015,6302,how could the universe be a few light-years ac...,shouldn't the universe be one light-second acr...,there is no speed limit on the rate of expansi...,1047,[],[],[http://m.youtube.com/#/watch?v=VNv0Yzk00qg&am...,"[0.12889410555362701, 0.7120699882507324, 0.69..."
6016,6303,if our universe is expanding at certain rate w...,consider this as a follow-up question to /r/as...,good question. here's an analogy. imagine you ...,581,[],[],[http://www.nat.vu.nl/~wimu/Varying-Constants-...,"[1.50416898727417, 2.8521416187286377, 1.76644..."

In [31]:
df2 = pandas.DataFrame( dataset['train'].filter(lambda example: example["answers.score"] >= 100))
len(df2)

6304